version: 1
engine_release: 1

hyperparameter:
    federated_learning_rounds: 1
    number_of_all_clients: 10   # known as `n` in article

    client_similarity_alfa: 0.5 # better to be 0.5 (change base on network density)