version: 1

#! the federated learning rounds is T1+T2
hyperparameter:
    number_of_all_clients: 10   # known as `n` in article
    number_of_rounds_in_the_first_stage: 5 # known as `T1` in article 
    number_of_rounds_in_the_second_stage: 10 # known as `T2` in article
    training_epochs: 1 # known as `E` in article
    training_learning_rate: 0.01 # known as `η` in article
    size_of_aggregation_neighbor_list: 5 # known as `k` in article
    size_of_neighbor_candidate_list: 3 # known as `l` in article
    round_interval_of_NAEM_in_the_second_stage: 2 # know as `τ` in article
    client_similarity_alfa: 0.5 # better to be 0.5 (change base on network density) known as `α` in paper

engine:
    release: 0.0.1
    
    grpc:
        timeout: 10 # float,   maximum time (seconds) to wait for a gRPC request.
    
    gossip:
        period: 0.1 # float, period (seconds) for the gossip protocol.
        ttl: 10 # int, period (seconds) for the gossip protocol.
        messages_per_period: 100 # int, number of messages to send in each gossip period.
        amount_last_messages_saved: 100 # int, umber of last messages saved in the gossip protocol (avoid multiple message processing).
        models_period: 1 # int, period of gossiping models (times by second).
        models_per_round: 2 # int, amount of equal rounds to exit gossiping. Careful, a low value can cause an early stop of gossiping.
        exit_on_x_equal_rounds: 10 # int, amount of equal rounds to exit gossiping. Careful, a low value can cause an early stop of gossiping.

    heartbeat:
        period: 2 # float, period (seconds) to send heartbeats 
        timeout: 5 # float, timeout (seconds) for a node to be considered dead.
    
    monitoring:
        resource_monitoring_period: 1 # int, period (seconds) to send resource monitor information. (web)



